let mySprite4: Sprite = null
let mySprite3: Sprite = null
let mySprite2: Sprite = null
let mySprite: Sprite = null
game.splash("2 villains have escaped from prison. You must hunt them down and recapture them!")
scene.cameraFollowSprite(mySprite)
scene.cameraFollowSprite(mySprite2)
scene.cameraFollowSprite(mySprite3)
scene.cameraFollowSprite(mySprite4)
mySprite = sprites.create(assets.image`Big Bore`, SpriteKind.Player)
mySprite2 = sprites.create(assets.image`Captain Creativity`, SpriteKind.Player)
mySprite3 = sprites.create(assets.image`Foolish Follower`, SpriteKind.Player)
mySprite4 = sprites.create(img`
    .................
    .................
    .................
    .................
    .................
    .................
    .................
    .................
    .................
    .................
    .................
    .................
    .................
    .................
    .................
    .................
    .................
    .................
    .................
    .................
    .................
    .................
    .................
    .................
    .................
    `, SpriteKind.Player)
controller.player1.moveSprite(mySprite)
controller.player2.moveSprite(mySprite2)
controller.player3.moveSprite(mySprite3)
controller.player4.moveSprite(mySprite4)
